"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LibraryBook_js_1 = require("./types/LibraryBook.js");
var book1 = { title: 'Братья Карамазовы', author: 'Ф. М. Достоевский', year: 1880 };
var book2 = { title: 'Идиот', author: 'Ф. М. Достоевский', year: 1869 };
var book3 = { title: 'Бесы', author: 'Ф. М. Достоевский', year: 1872 };
var libBook1 = new LibraryBook_js_1.LibraryBook(book1);
var libBook2 = new LibraryBook_js_1.LibraryBook(book2);
var libBook3 = new LibraryBook_js_1.LibraryBook(book3);
libBook1.borrow('Анна');
libBook2.borrow('Николай');
libBook3.borrow('Мария');
